eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerwitheureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: client1
  profiles:
    active: local

