eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 每间隔30s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 15
    # 告诉服务端，如果我60s之内没有给你发心跳，就代表我"死"了，将我踢出掉。
    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    registerwitheureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000

spring:
  application:
    name: client1
  profiles:
    active: local

